
GET http://localhost:3001/info/

###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons/2
###
GET http://localhost:3001/api/persons/3

###
DELETE http://localhost:3001/api/persons/5f738cf0f0277a4b127b82d93

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "JoJo",
  "number": "12-43-234345-2"
}